---
slug: example_book
filename: example_book
title: Title of the Book
subtitle: Change me
description: Change me.
author: Author Name
copyright: 2014
uuid: 18b6995c-8073-4065-baff-26e4a99c4e6b
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
